--  학생 테이블

CREATE TABLE TB_STUDENT (
	STUDENT_NO VARCHAR(10) CONSTRAINT TB_STUDENT_PK PRIMARY KEY,
	STUDENT_NAME VARCHAR2(30) NOT NULL,	
	STUDENT_DEPT VARCHAR2(50) NOT NULL,
	STUDENT_SSN DATE NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	POINT NUMBER,
	ENTRANCE_DATE DATE NOT NULL,
	ABSENCE_YN CHAR(1) DEFAULT 'N'
		CONSTRAINT ABSENCE_YN CHECK(ABSENCE_YN IN ('Y', 'N')),
	ABSENCE_DATE DATE ,
	GRADUATION_YN CHAR(1) DEFAULT 'N',
		CONSTRAINT GRADUATION_YN CHECK(GRADUATION_YN IN ('Y', 'N')),
	GRADUATION_DATE DATE
);

-- 주석 추가
COMMENT ON COLUMN TB_STUDENT.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STUDENT_DEPT IS '학과';
COMMENT ON COLUMN TB_STUDENT.STUDENT_SSN IS '생년월일';
COMMENT ON COLUMN TB_STUDENT.ADDRESS IS '학생 주소';
COMMENT ON COLUMN TB_STUDENT.POINT IS '학점';
COMMENT ON COLUMN TB_STUDENT.ENTRANCE_DATE IS '입학일';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_YN IS '휴학 여부(Y,N)';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_DATE IS '휴학일';
COMMENT ON COLUMN TB_STUDENT.GRADUATION_YN IS '졸업 여부(Y,N)';
COMMENT ON COLUMN TB_STUDENT.GRADUATION_DATE IS '졸업일';

CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;


INSERT INTO TB_STUDENT VALUES ('22001', '김이름', '경영학과','2003-06-07' ,'서울시 중구 남대문로', 3.5, '2022-03-04', DEFAULT, NULL, DEFAULT, NULL);
INSERT INTO TB_STUDENT VALUES ('21002', '이이름', '무역학과','2002-01-03' ,'경기도 수원시 팔달구', 4.2, '2021-03-02', 'Y', '2021-06-18', DEFAULT, NULL);
INSERT INTO TB_STUDENT VALUES ('20003', '박이름', '생명공학과','2000-02-03' , '강원도 춘천시 중앙로', 3.7, '2020-03-04', DEFAULT, NULL, DEFAULT, NULL);
INSERT INTO TB_STUDENT VALUES ('19004', '강이름', '소프트웨어융합과','2000-07-04', '충청북도 보령시 성주산로', 3.8, '2019-03-02', DEFAULT, NULL, 'Y', '2023-02-19');
INSERT INTO TB_STUDENT VALUES ('22005', '홍이름', '회계학과', '2022-12-28' ,'서울시 성동구 고산자로', '4.0', '2022-03-04', DEFAULT, NULL, DEFAULT, NULL);

SELECT * FROM TB_STUDENT;

COMMIT;

DROP TABLE TB_STUDENT ;


---------------------------------------------------------------------------------------------------------------------

-- 학생 전체 조회
SELECT STUDENT_NO ,STUDENT_NAME ,STUDENT_DEPT , TO_CHAR(STUDENT_SSN, 'YYYY-MM-DD') "STUDENT_SSN", ADDRESS , 
				POINT , TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "ENTRANCE_DATE", ABSENCE_YN , TO_CHAR(ABSENCE_DATE, 'YYYY-MM-DD') "ABSENCE_DATE", GRADUATION_YN, 
				TO_CHAR(GRADUATION_DATE, 'YYYY-MM-DD') "GRADUATION_DATE"
FROM TB_STUDENT;


-- 학생 정보 수정
UPDATE TB_STUDENT SET
STUDENT_DEPT = ?
ADDRESS = ?
POINT = ?
ABSENCE_YN =?
ABSENCE_DATE = ?
GRADUATION_YN = ?
GRADUATION_DATE = ?
WHERE STUDENT_NO =?;











