--  학생 테이블

CREATE TABLE TB_STUDENT (
	STUDENT_NO NUMBER CONSTRAINT TB_STUDENT_PK PRIMARY KEY,
	STUDENT_NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	POINT NUMBER,
	ENTRANCE_DATE DATE NOT NULL,
	ABSENCE_YN CHAR(1) DEFAULT 'N',
		CONSTRAINT ABSENCE_YN CHECK(ABSENCE_YN IN ('Y', 'N')),
	ABSENCE_DATE DATE 
);

-- 주석 추가
COMMENT ON COLUMN TB_STUDENT.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.ADDRESS IS '학생 주소';
COMMENT ON COLUMN TB_STUDENT.POINT IS '학점';
COMMENT ON COLUMN TB_STUDENT.ENTRANCE_DATE IS '입학일';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_YN IS '휴학 여부(Y,N)';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_DATE IS '휴학일';

CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;

INSERT INTO TB_STUDENT VALUES (001, '김이름', '서울시 중구 남대문로', 3.5, 2022-03-04, DEFAULT );

SELECT * FROM TB_STUDENT;

DROP TABLE TB_STUDENT ;

